In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from scipy.optimize import minimize


In [8]:
np.random.seed(0)
X = np.random.normal(0, 1, size=(100, 10))
betas = np.random.uniform(size=10)
Y = np.dot(X, betas) + np.random.normal(size=100)

def subset_shrinkage(beta, X, Y, lambda_ridge=0.1, idx_to_shrink=[]):
    mse = np.mean((Y - np.dot(X, beta))**2)

    ridge_penalty = lambda_ridge * np.sum(beta[idx_to_shrink]**2)
    
    return mse + ridge_penalty

initial_betas = np.zeros(X.shape[1])

# Minimize the objective function
subset_coef = minimize(subset_shrinkage, initial_betas, args=(X, Y, 0.1, [0])) #Penalise the first feature only

subset_coef.x 

array([ 0.73591131,  0.88466182,  1.18049127,  1.0664644 ,  0.73775562,
        0.84546585,  0.45763088, -0.01749775,  0.04705773,  0.328992  ])

In [24]:
def cluster_shrinkage(beta, X, Y, lambda_ridge=0.1):
    mse = np.mean((Y - np.dot(X, beta))**2)

    ridge_penalty = lambda_ridge * np.sum((beta - np.mean(beta))**2)
    
    return mse + ridge_penalty

cluster_coef = minimize(cluster_shrinkage, initial_betas, args=(X, Y, 1.0)) #Pulls them to the mean

cluster_coef.x 

array([0.72151918, 0.7146317 , 0.89864458, 0.88874064, 0.72399857,
       0.76522069, 0.56631377, 0.29299189, 0.34438384, 0.4965699 ])

In [27]:
def non_zero_priors(beta, X, Y, beta_priors, lambda_ridge=0.1):
    mse = np.mean((Y - np.dot(X, beta))**2)

    ridge_penalty = lambda_ridge * np.sum((beta - beta_priors))**2
    
    return mse + ridge_penalty

non_zero_coef = minimize(non_zero_priors, initial_betas, args=(X, Y, np.ones(10), 1.0))  ## Priors of the betas are 1

non_zero_coef.x 

array([1.12126818, 1.05547165, 1.54467606, 1.34636484, 1.13140441,
       1.19648692, 0.84105352, 0.35565933, 0.3298477 , 0.74072983])